Last run: 241115

Uses results from astroquery.xmatch because it has the most (conservative) matches compared to exofop or vizier cross-match methods. See details in `crossmatch_TOI_with_exofop_vizier.ipynb`.

In [1]:
import sys

!which {sys.executable}

/ut3/jerome/miniconda3/envs/wakai/bin/python

%load init_ipynb

In [2]:
import sys
sys.path.insert(0, '../code')

# Perren+2023 catalog

* [version 250204](https://zenodo.org/records/14801947)

https://ucc.ar/changelog/

Manual download from zenodo and upload to server

In [3]:
import pandas as pd

df = pd.read_csv('../data/Perren2023/UCC_cat.csv.gz')
df.tail()

,ID,RA_ICRS,DE_ICRS,plx,pmRA,pmDE,UCC_ID,N_50,r_50,RA_ICRS_m,DE_ICRS_m,plx_m,pmRA_m,pmDE_m,Rv_m,N_Rv,C1,C2,C3
16174,MKN 1;MKN ab,266.4468,-29.0874,NaN,NaN,NaN,UCC G359.8-00.1,79.0,4.4,266.462,-29.095,0.489,1.753,-0.777,-25.868,5.0,0.86,0.75,AA
16175,MWSC 5326,248.1925,-17.1430,NaN,NaN,NaN,UCC G359.9+20.4,0.0,4.6,248.189,-17.148,0.090,-3.735,-5.860,67.828,1.0,0.11,0.20,DD
16176,HSC 2986,285.3171,-36.8834,6.694,2.209,-27.556,UCC G359.9-17.7,0.0,22.5,285.298,-36.941,6.532,3.670,-27.737,-5.275,8.0,0.72,1.00,BA
16177,VVV 149;VVV-CL 149,267.3380,-29.4640,NaN,NaN,NaN,UCC G359.9-00.9,0.0,2.6,267.351,-29.455,0.352,-0.674,-2.780,-39.904,3.0,0.45,0.46,CC
16178,Ryu 535,266.5884,-29.0573,NaN,NaN,NaN,UCC G359.9-00.2,61.0,2.1,266.606,-29.055,0.376,-0.153,-2.099,-33.921,4.0,0.88,0.31,AC

In [4]:
df_mem = pd.read_parquet('../data/Perren2023/UCC_members.parquet.gz')
df_mem.tail()

,name,Source,RA_ICRS,DE_ICRS,Plx,e_Plx,pmRA,e_pmRA,pmDE,e_pmDE,RV,e_RV,GLON,GLAT,Gmag,BP-RP,e_Gmag,e_BP-RP,probs
1337412,ryu30,5933719906152539904,247.228085,-52.699637,0.240993,0.158018,-4.525831,0.154389,-4.983059,0.127764,NaN,NaN,332.477863,-2.781450,18.330563,2.435881,0.003246,0.088112,0.46891
1337413,ryu30,5933720318469495424,247.180385,-52.706245,0.135389,0.053207,-4.841031,0.055405,-5.292475,0.045611,NaN,NaN,332.453112,-2.765083,16.444132,1.731100,0.002817,0.009220,0.45149
1337414,ryu30,5933720107969318016,247.178643,-52.736859,0.300294,0.121510,-4.620295,0.120153,-5.140017,0.103496,NaN,NaN,332.430199,-2.785444,17.966627,1.370831,0.002976,0.017981,0.45149
1337415,ryu30,5933720490268392704,247.119139,-52.692309,0.270647,0.230620,-4.524732,0.220578,-4.939661,0.182071,NaN,NaN,332.437554,-2.728610,18.863051,2.578410,0.003619,0.063381,0.41418
1337416,ryu30,5933730587694794880,247.078632,-52.721215,0.231349,0.169833,-4.648944,0.173652,-4.778104,0.143794,NaN,NaN,332.399658,-2.730834,18.484586,NaN,0.003323,NaN,0.40547

In [5]:
#replace name to be compatible with other catalogs' naming formats
df_mem = df_mem.rename({"name": "Name",
                        "Source": "GaiaDR3",
                        "probs": "Prob",
                        "RA_ICRS": "ra",
                        "DE_ICRS": "dec",
                        "pmRA": "pmra",
                        "pmDE": "pmdec",
                        "Plx": "parallax",
                        "RV": "radial_velocity"
                        }, axis=1)
df_mem

,Name,GaiaDR3,ra,dec,parallax,e_Plx,pmra,e_pmRA,pmdec,e_pmDE,radial_velocity,e_RV,GLON,GLAT,Gmag,BP-RP,e_Gmag,e_BP-RP,Prob
0,teutsch288,2035397237977138688,297.899779,34.283035,0.145318,0.024893,-2.974327,0.023901,-5.158872,0.030316,-37.576607,4.797507,69.829982,3.785472,15.418702,2.254350,0.002774,0.005336,0.99767
1,teutsch288,2035389575755522944,297.965276,34.067585,0.145510,0.027632,-2.991828,0.030353,-5.123003,0.031205,NaN,NaN,69.671655,3.629290,15.662445,2.212796,0.002788,0.006342,0.98601
2,teutsch288,2035488463077136512,298.127866,34.400420,0.103535,0.027940,-3.008745,0.025883,-5.085567,0.030720,NaN,NaN,70.027281,3.683075,15.776573,2.014382,0.002781,0.005409,0.95804
3,teutsch288,2035393458405832448,298.028314,34.250542,0.288494,0.011875,-3.031625,0.012742,-5.184984,0.013464,-14.070918,0.746670,69.856073,3.677483,13.459954,2.037782,0.002763,0.004934,0.86946
4,teutsch288,2035491486734157440,298.106791,34.426259,0.070932,0.015924,-2.982798,0.014108,-5.185106,0.016694,-45.478336,1.353905,70.040681,3.711202,14.410107,2.713133,0.002785,0.005189,0.86946
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1337412,ryu30,5933719906152539904,247.228085,-52.699637,0.240993,0.158018,-4.525831,0.154389,-4.983059,0.127764,NaN,NaN,332.477863,-2.781450,18.330563,2.435881,0.003246,0.088112,0.46891
1337413,ryu30,5933720318469495424,247.180385,-52.706245,0.135389,0.053207,-4.841031,0.055405,-5.292475,0.045611,NaN,NaN,332.453112,-2.765083,16.444132,1.731100,0.002817,0.009220,0.45149
1337414,ryu30,5933720107969318016,247.178643,-52.736859,0.300294,0.121510,-4.620295,0.120153,-5.140017,0.103496,NaN,NaN,332.430199,-2.785444,17.966627,1.370831,0.002976,0.017981,0.45149
1337415,ryu30,5933720490268392704,247.119139,-52.692309,0.270647,0.230620,-4.524732,0.220578,-4.939661,0.182071,NaN,NaN,332.437554,-2.728610,18.863051,2.578410,0.003619,0.063381,0.41418
1337416,ryu30,5933730587694794880,247.078632,-52.721215,0.231349,0.169833,-4.648944,0.173652,-4.778104,0.143794,NaN,NaN,332.399658,-2.730834,18.484586,NaN,0.003323,NaN,0.40547

# cross-match TOI with Gaia DR3 using `astroquery.xmatch`

In [7]:
import pandas as pd

matches = pd.read_csv('../data/TOIs_GaiaDR3_xmatch.csv')
matches.tail()

,angDist,TIC ID,TOI,Previous CTOI,Master,SG1A,SG1B,SG2,SG3,SG4,...,E(BP-RP),b_E(BP-RP),B_E(BP-RP),Lib,RAJ2000,DEJ2000,e_RAJ2000,e_DEJ2000,RADEcorJ2000,GaiaDR3
7620,0.018288,352301423,7334.01,NaN,3,4,3,3,1,4,...,0.0546,0.0466,0.0626,MARCS,297.182251,58.384445,1.009054,1.241652,-0.0370,2235759867479720064
7621,0.043186,75417968,7335.01,NaN,3,4,3,3,1,4,...,0.0707,0.0401,0.0771,MARCS,308.688932,17.403665,0.358187,0.385483,0.4412,1811847724940677376
7622,0.091872,271017537,7336.01,NaN,1,4,1,1,1,4,...,0.0000,0.0000,0.0002,MARCS,353.525357,65.540835,0.208975,0.171382,-0.2766,2209478481561200256
7623,0.018481,323407659,7337.01,NaN,3,4,3,3,1,4,...,0.1658,0.1603,0.1703,MARCS,333.355327,67.394162,0.245584,0.216391,-0.1757,2219776919780767360
7624,0.044777,309133240,7338.01,TIC 309133240.01,1,4,1,1,2,4,...,0.0005,0.0001,0.0020,PHOENIX,25.226082,50.300017,0.254575,0.253889,0.0115,405785280312141312

In [8]:
matches.shape

(7625, 205)

matches.columns.tolist()

In [9]:
final = pd.merge(df_mem, matches, on='GaiaDR3').sort_values(by='TOI', ascending=False)
final.head()

,Name,GaiaDR3,ra,dec,parallax,e_Plx_x,pmra,e_pmRA_x,pmdec,e_pmDE_x,...,B_AG,E(BP-RP),b_E(BP-RP),B_E(BP-RP),Lib,RAJ2000,DEJ2000,e_RAJ2000,e_DEJ2000,RADEcorJ2000
49,melotte102,5239758155778687360,159.157963,-64.798229,6.645880,0.009345,-17.586064,0.010087,10.490284,0.009769,...,0.2972,0.1554,0.1525,0.1580,MARCS,159.158146,-64.798276,0.162185,0.155878,0.1012
39,hsc2675,5895008644342480640,220.003903,-52.910050,2.075726,0.016708,0.945049,0.011998,-9.141739,0.017933,...,0.3653,0.1948,0.1856,0.1980,MARCS,220.003896,-52.910009,0.194080,0.284870,-0.6194
18,ascc123,2003378188041736320,338.805335,54.773556,4.234836,0.016065,12.197541,0.016069,-0.575995,0.016105,...,0.0988,0.0508,0.0478,0.0534,MARCS,338.805241,54.773559,0.258210,0.257853,-0.2737
17,ascc123,2003378188041736320,338.805335,54.773556,4.234836,0.016065,12.197541,0.016069,-0.575995,0.016105,...,0.0988,0.0508,0.0478,0.0534,MARCS,338.805241,54.773559,0.258210,0.257853,-0.2737
16,ascc123,2003378188041736320,338.805335,54.773556,4.234836,0.016065,12.197541,0.016069,-0.575995,0.016105,...,0.0988,0.0508,0.0478,0.0534,MARCS,338.805241,54.773559,0.258210,0.257853,-0.2737

In [10]:
final.shape

(53, 223)

In [11]:
new_cols = "TOI	TIC ID	Name	GaiaDR3	Prob	TESS Disposition	TFOPWG Disposition	Comments	TESS Mag	TESS Mag err	Source_1	Detection	Epoch (BJD)	Epoch (BJD) err	Period (days)	Period (days) err	Duration (hours)	Duration (hours) err	Depth (mmag)	Depth (mmag) err	Depth (ppm)	Depth (ppm) err	Planet Radius (R_Earth)	Planet Radius (R_Earth) err	Planet Insolation (Earth Flux)	Planet Equil Temp (K)	Planet SNR	Stellar Distance (pc)	Stellar Distance (pc) err	Stellar Eff Temp (K)	Stellar Eff Temp (K) err	Stellar log(g) (cm/s^2)	Stellar log(g) (cm/s^2) err	Stellar Radius (R_Sun)	Stellar Radius (R_Sun) err	Stellar Metallicity	Stellar Metallicity err	Stellar Mass (M_Sun)	Stellar Mass (M_Sun) err	Sectors	Date TOI Alerted (UTC)	Date TOI Updated (UTC)	Date Modified	ra_deg	dec_deg	Pipeline Signal ID	RA	Dec	PM RA (mas/yr)	PM RA err (mas/yr)	PM Dec (mas/yr)	PM Dec err (mas/yr)	DR3Name	RAdeg	DEdeg	errHalfMaj	errHalfMin	errPosAng	SolID	Source_2	RandomI	e_RAdeg	e_DEdeg	RPlx	PM	RADEcor	RAPlxcor	RApmRAcor	RApmDEcor	DEPlxcor	DEpmRAcor	DEpmDEcor	PlxpmRAcor	PlxpmDEcor	pmRApmDEcor	NAL	NAC	NgAL	NbAL	gofAL	chi2AL	epsi	sepsi	Solved	APF	nueff	MatchObsA	Nper	amax	MatchObs	IPDgofha	IPDgofhp	IPDfmp	IPDfow	RUWE	Dup	o_Gmag	FG	e_FG	RFG	Gmag_y	o_BPmag	FBP	e_FBP	RFBP	e_BPmag	o_RPmag	FRP	e_FRP	RFRP	e_RPmag	E(BP/RP)	NBPcont	NBPblend	NRPcont	NRPblend	Mode	BP-G	G-RP	n_RV	o_RV	o_RVd	RVNper	RVS/N	RVgof	RVchi2	RVTdur	RVamp	RVtempTeff	RVtemplogg	RVtemp[Fe/H]	Vatmparam	vbroad	e_Vbroad	o_Vbroad	GRVSmag	e_GRVSmag	o_GRVSmag	RVSS/N	VarFlag	PQSO	PGal	PSS	Teff	b_Teff	B_Teff	logg	b_logg	B_logg	[Fe/H]	b_[Fe/H]	B_[Fe/H]	Dist	b_Dist	B_Dist	A0	b_A0	B_A0	AG	b_AG	B_AG	E(BP-RP)	b_E(BP-RP)	B_E(BP-RP)	Lib	RAJ2000	DEJ2000	e_RAJ2000	e_DEJ2000	RADEcorJ2000	Previous CTOI	Master	SG1A	SG1B	SG2	SG3	SG4	SG5	ESM	TSM	Predicted Mass (M_Earth)	Time Series Observations	Spectroscopy Observations	Imaging Observations".split('\t')

In [12]:
final[new_cols].head()

,TOI,TIC ID,Name,GaiaDR3,Prob,TESS Disposition,TFOPWG Disposition,Comments,TESS Mag,TESS Mag err,...,SG2,SG3,SG4,SG5,ESM,TSM,Predicted Mass (M_Earth),Time Series Observations,Spectroscopy Observations,Imaging Observations
49,6715.01,460950389,melotte102,5239758155778687360,1.0,PC,PC,host is a BY Dra variable star; low MES,11.6490,0.006,...,2,3,4,4,10.8,67.3,14.54,3,0,4
39,6705.01,379717270,hsc2675,5895008644342480640,1.0,PC,PC,variable host; multiple stars in pixel,10.2734,0.006,...,3,1,4,4,56.8,86.0,317.00,3,0,0
18,6650.04,64837857,ascc123,2003378188041736320,1.0,PC,PC,single transit at TBJD ~2878; potential multi,10.0252,0.006,...,3,4,4,4,NaN,NaN,23.72,2,29,5
17,6650.03,64837857,ascc123,2003378188041736320,1.0,PC,PC,potential multi,10.0252,0.006,...,3,4,4,4,5.1,42.5,16.97,2,29,5
16,6650.02,64837857,ascc123,2003378188041736320,1.0,PC,PC,potential multi near 3:2 resonance,10.0252,0.006,...,3,4,4,4,3.8,40.9,27.50,2,29,5

In [17]:
final[new_cols].to_csv('../data/Perren2023/TOIs_in_Perren2023.csv', index=False)