In [1]:
import sys

!which {sys.executable}

/ut3/jerome/miniconda3/envs/wakai/bin/python

In [2]:
import sys
sys.path.insert(0, '../code')

%load init_ipynb

# Ratzenboeck2023+2023 catalog

In [4]:
import sys
sys.path.insert(0, '../code')
from catalog import CatalogDownloader

cd = CatalogDownloader(catalog_name="Ratzenboeck2023a", catalog_type="cluster")
tabs = cd.get_tables_from_vizier(row_limit=-1, save=True)

2025-07-25 14:55:37.489 | INFO     | catalog:get_vizier_url:1206 - Data url: https://vizier.u-strasbg.fr/viz-bin/VizieR?-source=J/A%2bA/677/A59
2025-07-25 14:55:37.491 | INFO     | catalog:get_tables_from_vizier:1158 - Downloading all tables in J/A%2bA/677/A59 from vizier.
2025-07-25 14:55:39.794 | INFO     | catalog:save_tables:1195 - Saved: /ut2/jerome/github/research/project/wakai/data/Ratzenboeck2023a/Ratzenboeck2023a_tab0.txt

{'J/A+A/677/A59/table3': 'Overview of the 37 SigMA clusters in Sco-Cen, '
                         'assigned to seven subregions',
 'J/A+A/677/A59/tablee1': 'Sco-Cen cluster information'}

2025-07-25 14:55:40.331 | INFO     | catalog:save_tables:1195 - Saved: /ut2/jerome/github/research/project/wakai/data/Ratzenboeck2023a/Ratzenboeck2023a_tab1.txt

In [7]:
df = tabs[0].to_pandas()
df.head()

,SigMA,Region,Group,Bstar,Nr,GLON,GLAT,plx,Dist,X,Y,Z,_RA.icrs,_DE.icrs
0,1,US,rho Oph/L1688,* rho Oph,535,353.200012,17.090000,7.20,139,132,-16,41,246.5512,-24.1895
1,2,US,nu Sco,* nu Sco,150,354.459991,22.860001,7.18,139,128,-12,54,242.7757,-19.4546
2,3,US,delta Sco,* b Sco,691,350.250000,22.180000,7.03,142,130,-22,54,240.4300,-22.7406
3,4,US,beta Sco,HD142883,285,353.209991,23.530001,6.49,154,141,-17,61,241.4246,-19.8418
4,5,US,sigma Sco,* c02 Sco,544,351.130005,17.870001,6.29,159,149,-24,49,244.4574,-25.1308

In [5]:
df_mem = tabs[1].to_pandas()
df_mem.head()

,GaiaDR3,SigMA,stability,Dist,X,Y,Z,VtRA,VtDE,VtRALSR,VtDELSR,RV,_RA,_DE
0,3459372646830687104,21,13.3,64.6731,24.0949,-54.656,24.7942,-19.629999,-7.259,-3.095,-0.911,11.532,181.88908,-39.54844
1,3459442092158725760,21,25.5,124.9500,45.8469,-105.650,48.4526,-17.969999,-7.174,-1.419,-0.865,11.562,181.56496,-39.22292
2,3459492631038236416,21,9.8,65.6421,24.3025,-55.277,25.7430,-19.780001,-7.615,-3.246,-1.223,11.433,181.95111,-39.00135
3,3459725624422311424,21,7.8,82.1535,29.1810,-69.412,32.8575,-19.570000,-7.270,-3.007,-1.013,11.570,180.99576,-38.36128
4,3460673098504625024,21,3.6,123.4010,41.9837,-104.060,51.3561,-18.740000,-8.151,-2.170,-1.942,11.560,180.32367,-37.20920

cd2 = CatalogDownloader(catalog_name="Ratzenboeck2023b", catalog_type="cluster")
tabs2 = cd2.get_tables_from_vizier(row_limit=-1, save=True)

#replace name to be compatible with other catalogs' naming formats
df_mem = df_mem.rename({"Cluster": "Name",
                        "Source": "GaiaDR3",
                        "Proba": "Prob",
                        "RA_ICRS": "ra",
                        "DE_ICRS": "dec",
                        "pmRA": "pmra",
                        "pmDE": "pmdec",
                        "Plx": "parallax",
                        "RV": "radial_velocity"
                        }, axis=1)
df_mem.head()

In [8]:
from catalog import get_tois

tois = get_tois(clobber=False)
# tois.columns.tolist()

tois[tois.Comments.apply(lambda x: 'young' in str(x))]

# cross-match TOI with Gaia DR3 using `astroquery.xmatch`

!{sys.executable} -m pip show astroquery

!{sys.executable} -m pip install mocpy -U

https://astroquery.readthedocs.io/en/latest/xmatch/xmatch.html

In [9]:
import pandas as pd

# output of cross_match_TOI_with_GaiaDR3.ipynb
matches = pd.read_csv('../data/TOIs_GaiaDR3_xmatch.csv')
matches.head()

,angDist,TIC ID,TOI,Previous CTOI,Master,SG1A,SG1B,SG2,SG3,SG4,...,E(BP-RP),b_E(BP-RP),B_E(BP-RP),Lib,RAJ2000,DEJ2000,e_RAJ2000,e_DEJ2000,RADEcorJ2000,GaiaDR3
0,0.031583,231663901,101.01,NaN,5,5,5,5,5,5,...,0.0088,0.0015,0.0438,MARCS,318.736916,-55.871794,0.183824,0.186203,-0.0885,6462994429708755072
1,0.029564,149603524,102.01,NaN,5,5,5,5,5,5,...,0.0005,0.0001,0.0013,MARCS,87.139972,-63.988441,0.270854,0.243980,-0.2165,4756649415309914240
2,0.035823,336732616,103.01,NaN,5,5,5,5,5,5,...,0.0180,0.0144,0.0210,MARCS,312.457439,-24.428761,0.282852,0.230957,0.4094,6805886373600546176
3,0.016955,231670397,104.01,NaN,5,5,5,5,5,5,...,NaN,NaN,NaN,NaN,319.949611,-58.148887,0.213587,0.200585,-0.1912,6453566701615683456
4,0.024290,144065872,105.01,NaN,5,5,5,5,5,5,...,0.0174,0.0136,0.0234,MARCS,337.457231,-48.003069,0.180076,0.230102,0.1517,6518399301667782016

In [10]:
matches.shape

(7760, 205)

In [11]:
matches.loc[:, 'GaiaDR3'] = matches['DR3Name'].apply(lambda x: int(x.split()[-1]))
final = pd.merge(df_mem, matches, on='GaiaDR3')
final.head()

,GaiaDR3,SigMA,stability,Dist_x,X,Y,Z,VtRA,VtDE,VtRALSR,...,B_AG,E(BP-RP),b_E(BP-RP),B_E(BP-RP),Lib,RAJ2000,DEJ2000,e_RAJ2000,e_DEJ2000,RADEcorJ2000
0,5838183443852841216,23,100.000000,102.1640,50.3013,-86.143,-22.05800,-19.049999,-3.612000,-2.534,...,0.8512,0.5985,0.5967,0.6002,MARCS,182.726847,-75.131897,0.347051,0.374272,0.1217
1,5842480953772012928,23,100.000000,100.9630,51.3681,-85.249,-16.95600,-19.290001,-5.173000,-2.925,...,0.8510,0.6017,0.5502,0.6138,MARCS,186.767939,-72.451804,0.421471,0.477243,0.1098
2,6005795195418914816,17,95.300003,156.3890,134.1420,-70.746,38.18850,-13.400000,-15.550000,-3.634,...,0.7071,0.4617,0.4544,0.4821,MARCS,231.025135,-39.909303,0.834855,0.711092,-0.2435
3,6025147218543620480,8,100.000000,152.9620,145.6500,-34.107,31.94130,-7.252000,-16.709999,-1.304,...,0.0212,0.0065,0.0027,0.0114,MARCS,246.057792,-32.143690,0.377305,0.341037,-0.3613
4,6055854551117476480,21,87.199997,95.0564,54.6611,-77.659,4.12448,-17.920000,-8.995000,-2.349,...,0.0410,0.0023,0.0002,0.0222,A,197.317469,-60.308349,0.281140,0.337569,0.3273

In [12]:
final.shape

(7, 218)

In [15]:
new_cols = "TOI	TIC ID	GaiaDR3	TESS Disposition	TFOPWG Disposition	Comments	TESS Mag	TESS Mag err	Source_1	Detection	Epoch (BJD)	Epoch (BJD) err	Period (days)	Period (days) err	Duration (hours)	Duration (hours) err	Depth (mmag)	Depth (mmag) err	Depth (ppm)	Depth (ppm) err	Planet Radius (R_Earth)	Planet Radius (R_Earth) err	Planet Insolation (Earth Flux)	Planet Equil Temp (K)	Planet SNR	Stellar Distance (pc)	Stellar Distance (pc) err	Stellar Eff Temp (K)	Stellar Eff Temp (K) err	Stellar log(g) (cm/s^2)	Stellar log(g) (cm/s^2) err	Stellar Radius (R_Sun)	Stellar Radius (R_Sun) err	Stellar Metallicity	Stellar Metallicity err	Stellar Mass (M_Sun)	Stellar Mass (M_Sun) err	Sectors	Date TOI Alerted (UTC)	Date TOI Updated (UTC)	Date Modified	ra_deg	dec_deg	Pipeline Signal ID	RA	Dec	PM RA (mas/yr)	PM RA err (mas/yr)	PM Dec (mas/yr)	PM Dec err (mas/yr)	DR3Name	RAdeg	DEdeg	errHalfMaj	errHalfMin	errPosAng	SolID	Source_2	RandomI	e_RAdeg	e_DEdeg	e_Plx	RPlx	PM	e_pmRA	e_pmDE	RADEcor	RAPlxcor	RApmRAcor	RApmDEcor	DEPlxcor	DEpmRAcor	DEpmDEcor	PlxpmRAcor	PlxpmDEcor	pmRApmDEcor	NAL	NAC	NgAL	NbAL	gofAL	chi2AL	epsi	sepsi	Solved	APF	nueff	MatchObsA	Nper	amax	MatchObs	IPDgofha	IPDgofhp	IPDfmp	IPDfow	RUWE	Dup	o_Gmag	FG	e_FG	RFG	e_Gmag	o_BPmag	FBP	e_FBP	RFBP	e_BPmag	o_RPmag	FRP	e_FRP	RFRP	e_RPmag	E(BP/RP)	NBPcont	NBPblend	NRPcont	NRPblend	Mode	BP-G	G-RP	e_RV	n_RV	o_RV	o_RVd	RVNper	RVS/N	RVgof	RVchi2	RVTdur	RVamp	RVtempTeff	RVtemplogg	RVtemp[Fe/H]	Vatmparam	vbroad	e_Vbroad	o_Vbroad	GRVSmag	e_GRVSmag	o_GRVSmag	RVSS/N	VarFlag	PQSO	PGal	PSS	Teff	b_Teff	B_Teff	logg	b_logg	B_logg	[Fe/H]	b_[Fe/H]	B_[Fe/H]	b_Dist	B_Dist	A0	b_A0	B_A0	AG	b_AG	B_AG	E(BP-RP)	b_E(BP-RP)	B_E(BP-RP)	Lib	RAJ2000	DEJ2000	e_RAJ2000	e_DEJ2000	RADEcorJ2000	Previous CTOI	Master	SG1A	SG1B	SG2	SG3	SG4	SG5	ESM	TSM	Predicted Mass (M_Earth)	Time Series Observations	Spectroscopy Observations	Imaging Observations".split('\t')

In [16]:
final[new_cols].to_csv(f'../data/{cd.catalog_name}/TOIs_in_{cd.catalog_name}.csv', index=False)

In [17]:
final[new_cols].sort_values(by='TOI', ascending=False)

,TOI,TIC ID,GaiaDR3,TESS Disposition,TFOPWG Disposition,Comments,TESS Mag,TESS Mag err,Source_1,Detection,...,SG2,SG3,SG4,SG5,ESM,TSM,Predicted Mass (M_Earth),Time Series Observations,Spectroscopy Observations,Imaging Observations
3,7038.01,210904767,6025147218543620480,PC,PC,variable host,8.9498,0.006,qlp-s65-210904767,SPOC/QLP,...,4,1,4,4,4.3,49.8,9.97,0,2,0
5,6697.02,441546821,6055854551117476480,PC,PC,possible additional planet in HD 114082 star s...,7.7897,0.006,spoc-s01-s65-b02,SPOC,...,3,3,4,4,NaN,NaN,110.91,3,2,2
4,6697.01,441546821,6055854551117476480,CP,CP,single transit of HD 114082 b,7.7897,0.006,spoc-CTOIs,CTOI,...,5,4,5,5,NaN,NaN,50.35,3,2,2
2,6626.01,148691985,6005795195418914816,PC,PC,found in faint-star QLP search,14.6186,0.009,qlp-s65-faintsearch,FAINT,...,3,1,4,4,133.3,249.5,125.34,3,0,0
6,6551.01,166527623,6113920619134019456,CP,KP,HIP 67522 b,9.1871,0.006,spoc-s64-b02,SPOC,...,5,5,5,5,49.5,188.3,64.55,3,57,1
0,1880.01,359357695,5838183443852841216,PC,PC,crowded field; v-shaped transits; CTOI from Lu...,13.0614,0.008,spoc-s01-s65-b0A-PC,CTOI,...,3,3,4,4,61.1,170.2,53.92,7,0,2
1,1227.01,360156606,5842480953772012928,CP,CP,TOI-1227 b,13.8020,0.008,spoc-s01-s65-b0A-CP,SPOC,...,3,4,4,4,0.6,52.3,34.17,13,0,4