Idea: 
* cross-match Kepler-K2-NExSci planets with Hunt+23 cluster members based on Gaia-Kepler.fun GAIA ID results
* check those planets if previously unknown to be young
  - e.g. using tql, check if such young RV systems have new transiting planets if recently observed by TESS

## TOI catalog

In [16]:
from astropy.table import Table

fp = "../data/kepler_dr3_good.fits"
kepler = Table.read(fp, format='fits')
df_kep = kepler.to_pandas()
df_kep.head()

WARNING: UnitsWarning: 'log(cm.s**-2)' did not parse as fits unit: 'log' is not a recognized function If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]
WARNING: UnitsWarning: 'dex' did not parse as fits unit: At col 0, Unit 'dex' not supported by the FITS standard.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]

,kepid,ra_kic,dec_kic,source_id,random_index,ra,dec,parallax,parallax_error,parallax_over_error,...,mass_err2,prov_sec,nconfp,nkoi,ntce,jmag,hmag,kmag,planet?,kepler_gaia_mag_diff
0,757076,291.03873,36.598129,2050233803028318080,770401191,291.038680,36.598029,1.474977,0.011027,133.760956,...,-0.475,b'DSEP',0,0,0,10.126,9.667,9.559,b'none',-0.076219
1,757099,291.04306,36.593811,2050233601176543104,187127310,291.043058,36.593767,2.798592,0.031155,89.828781,...,-0.233,b'DSEP',0,0,1,11.656,11.193,11.094,b'none',-0.072974
2,757137,291.05588,36.559952,2050230543159814656,391020929,291.055891,36.559885,1.754854,0.010898,161.022797,...,-0.947,b'DSEP',0,0,0,7.467,6.853,6.722,b'none',-0.063634
3,757280,291.09540,36.564941,2050230611879323904,219215210,291.095373,36.564902,1.122922,0.010995,102.132317,...,-0.157,b'DSEP',0,0,0,10.852,10.662,10.627,b'none',-0.131530
4,757450,291.13760,36.577381,2050231848829944320,189196887,291.137622,36.577344,1.231338,0.020312,60.619961,...,-0.040,b'DSEP',1,1,1,13.665,13.262,13.118,b'conf',-0.104204

In [32]:
fp = "../data/k2_dr2_1arcsec.fits"
k2 = Table.read(fp, format='fits')
df_k2 = k2.to_pandas()
df_k2.head()

,solution_id,designation,source_id,random_index,gaia_ref_epoch,ra,ra_error,dec,dec_error,parallax,...,k2_raderr2,k2_mass,k2_masserr1,k2_masserr2,k2_kepmag,k2_kepmagerr,k2_kepmagflag,k2c_disp,k2c_note,k2_gaia_ang_dist
0,1635721458409799680,b'Gaia DR2 2641087471777046016',2641087471777046016,74252976,2015.5,353.616269,0.034768,-1.579985,0.027861,2.841339,...,NaN,NaN,NaN,NaN,11.500,<NA>,b'N/A',b'N/A',b'N/A',0.140346
1,1635721458409799680,b'Gaia DR2 2634212328648066560',2634212328648066560,202647685,2015.5,352.388214,0.042030,-3.768873,0.031351,3.260346,...,NaN,NaN,NaN,NaN,11.514,<NA>,b'N/A',b'N/A',b'N/A',0.216362
2,1635721458409799680,b'Gaia DR2 2740066749756528384',2740066749756528384,1184521614,2015.5,1.157646,0.040951,3.550331,0.021344,1.232810,...,NaN,NaN,NaN,NaN,14.530,<NA>,b'N/A',b'N/A',b'N/A',0.319951
3,1635721458409799680,b'Gaia DR2 2545233735990589312',2545233735990589312,43090558,2015.5,4.170978,0.064219,-0.157038,0.045212,1.598753,...,NaN,NaN,NaN,NaN,16.388,<NA>,b'N/A',b'N/A',b'N/A',0.182060
4,1635721458409799680,b'Gaia DR2 2436283193217778176',2436283193217778176,488998495,2015.5,356.826395,0.059321,-8.086693,0.045740,2.918122,...,NaN,NaN,NaN,NaN,10.400,<NA>,b'N/A',b'N/A',b'N/A',0.027673

In [33]:
fp = "../data/exoplanets_dr2_1arcsec.fits"
nexsci = Table.read(fp, format='fits')
df_nexsci = nexsci.to_pandas()
df_nexsci.head()

,solution_id,designation,source_id,random_index,gaia_ref_epoch,ra,ra_error,dec,dec_error,parallax,...,pl_cbflag,pl_disc,hd_name,hip_name,st_radv,st_radverr1,st_radverr2,st_radvlim,st_radvn,nasa_gaia_ang_dist
0,1635721458409799680,b'Gaia DR2 3946945413106333696',3946945413106333696,221573267,2015.5,185.178779,0.162032,17.793252,0.131688,10.710445,...,0,2007,b'HD 107383',b'HIP 60202',43.37,0.21,-0.21,0,1,0.017243
1,1635721458409799680,b'Gaia DR2 1696798367260229376',1696798367260229376,91495763,2015.5,229.274595,0.122354,71.823943,0.110681,7.953881,...,0,2009,b'HD 136726',b'HIP 74793',-17.52,0.15,-0.15,0,1,0.014335
2,1635721458409799680,b'Gaia DR2 1920113512486282240',1920113512486282240,162105136,2015.5,352.824150,0.106518,39.235837,0.074691,13.228880,...,0,2008,b'HD 221345',b'HIP 116076',-59.73,0.31,-0.31,0,1,0.050127
3,1635721458409799680,b'Gaia DR2 1385293808145621504',1385293808145621504,1155875906,2015.5,242.602101,0.019262,43.816362,0.019824,55.736347,...,0,2002,b'HD 145675',b'HIP 79248',NaN,NaN,NaN,<NA>,5,0.038616
4,1635721458409799680,b'Gaia DR2 2135550755683407232',2135550755683407232,166057510,2015.5,295.465642,0.022583,50.516824,0.024786,47.275421,...,0,1996,b'HD 186427',b'HIP 96901',-28.10,0.10,-0.10,0,4,0.005876

## cluster catalog

In [3]:
import pandas as pd

#https://ucc.ar/faq/#where-is-the-full-database
df = pd.read_parquet("../data/UCC_members.parquet.gz")
df.shape

(1211230, 19)

In [86]:
idx=df.Source.isin(df_kep.source_id)
idx.sum()

1271

In [89]:
ids = df[idx][df[idx].probs>0.99].Source.values
idx2=df_kep.source_id.isin(ids)
kep_cluster_mem = df_kep[idx2]
kep_cluster_mem['planet?'].unique()

array([b'none', b'cand', b'conf'], dtype=object)

In [102]:
kep_cluster_mem[kep_cluster_mem["planet?"]==b'cand'].shape

(53, 86)

In [96]:
kep_cluster_mem[kep_cluster_mem["planet?"]==b'conf']

,kepid,ra_kic,dec_kic,source_id,random_index,ra,dec,parallax,parallax_error,parallax_over_error,...,mass_err2,prov_sec,nconfp,nkoi,ntce,jmag,hmag,kmag,planet?,kepler_gaia_mag_diff
10962,3440118,290.44067,38.523560,2052827207364859264,915335752,290.440629,38.523572,3.056519,0.009273,329.625092,...,-0.080,b'DSEP',1,1,1,11.456,11.152,11.107,b'conf',-0.018630
58347,6184894,284.05667,41.576729,2103737241426734336,645347848,284.056668,41.576728,3.008675,0.031928,94.232384,...,-0.034,b'DSEP',1,1,6,11.690,11.298,11.194,b'conf',-0.006441
106132,8331612,301.27869,44.250530,2081880913079644288,116168019,301.278685,44.250511,0.668770,0.027363,24.440327,...,-0.130,b'DSEP',1,2,2,14.521,14.175,14.039,b'conf',-0.014050
133661,9532052,294.15332,46.166439,2128112181565948800,989254705,294.153350,46.166396,0.873428,0.034371,25.411961,...,-0.058,b'DSEP',1,1,1,14.741,14.341,14.155,b'conf',0.017167
143105,9836149,293.98157,46.687752,2128198836827103616,506368669,293.981537,46.687727,0.842982,0.020533,41.054386,...,-0.076,b'DSEP',1,1,1,14.021,13.689,13.621,b'conf',-0.062586

In [104]:
ids = kep_cluster_mem[kep_cluster_mem["planet?"]==b'conf'].source_id
cols=['pl_hostname','pl_discmethod','st_teff','pl_radj','pl_bmassj','source_id']
df_nexsci.loc[df_nexsci.source_id.isin(ids),cols]

,pl_hostname,pl_discmethod,st_teff,pl_radj,pl_bmassj,source_id
1881,b'Kepler-1627',b'Transit',5445.0,0.329,NaN,2103737241426734336
2954,b'Kepler-66',b'Transit',5962.0,0.250,NaN,2128198836827103616
2965,b'Kepler-67',b'Transit',5331.0,0.262,NaN,2128112181565948800

what planet is `2052827207364859264` and `2081880913079644288`?

In [66]:
idx2=df.Source.isin(df_k2.source_id)
idx2.sum()

4268

In [74]:
ids = df[idx2][df[idx2].probs>0.99].Source.values
idx=df_k2.source_id.isin(ids)
df_k2[idx]

,solution_id,designation,source_id,random_index,gaia_ref_epoch,ra,ra_error,dec,dec_error,parallax,...,k2_raderr2,k2_mass,k2_masserr1,k2_masserr2,k2_kepmag,k2_kepmagerr,k2_kepmagflag,k2c_disp,k2c_note,k2_gaia_ang_dist
69,1635721458409799680,b'Gaia DR2 2739498199165473920',2739498199165473920,1053036873,2015.5,359.601032,0.044748,2.297961,0.022776,8.319842,...,NaN,NaN,NaN,NaN,10.280,<NA>,b'N/A',b'N/A',b'N/A',0.083623
546,1635721458409799680,b'Gaia DR2 2739304616399290624',2739304616399290624,1219929969,2015.5,1.196078,0.056382,3.339946,0.036465,7.861148,...,NaN,NaN,NaN,NaN,14.700,<NA>,b'N/A',b'N/A',b'N/A',0.065893
555,1635721458409799680,b'Gaia DR2 2643397309484516608',2643397309484516608,240355190,2015.5,356.905152,0.052730,1.393554,0.031631,8.109843,...,NaN,NaN,NaN,NaN,14.700,<NA>,b'N/A',b'N/A',b'N/A',0.107597
33358,1635721458409799680,b'Gaia DR2 3425501538301403904',3425501538301403904,1610179303,2015.5,92.368896,0.029134,23.979602,0.026721,1.097839,...,NaN,NaN,NaN,NaN,14.600,<NA>,b'N/A',b'N/A',b'N/A',0.161175
33359,1635721458409799680,b'Gaia DR2 3425499618453642112',3425499618453642112,1407501548,2015.5,92.259897,0.032458,23.921337,0.031127,1.157073,...,NaN,NaN,NaN,NaN,15.200,<NA>,b'N/A',b'N/A',b'N/A',0.038670
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
398213,1635721458409799680,b'Gaia DR2 6252667269888057728',6252667269888057728,1574031377,2015.5,229.377288,0.040593,-20.949587,0.029413,0.072017,...,NaN,NaN,NaN,NaN,12.915,<NA>,b'gri',b'N/A',b'N/A',0.030454
398215,1635721458409799680,b'Gaia DR2 6252667098089361536',6252667098089361536,600243125,2015.5,229.394109,0.046006,-20.949166,0.029416,0.081731,...,NaN,NaN,NaN,NaN,14.973,<NA>,b'JHK',b'N/A',b'N/A',0.038939
398268,1635721458409799680,b'Gaia DR2 6252679089638054912',6252679089638054912,734657614,2015.5,229.350139,0.046878,-20.929823,0.034263,0.070376,...,NaN,NaN,NaN,NaN,15.694,<NA>,b'JHK',b'N/A',b'N/A',0.102456
420725,1635721458409799680,b'Gaia DR2 661270898815358720',661270898815358720,1226433210,2015.5,129.901875,0.140348,19.512072,0.090344,5.416848,...,NaN,NaN,NaN,NaN,17.753,<NA>,b'N/A',b'N/A',b'N/A',0.137907
420726,1635721458409799680,b'Gaia DR2 661311267210542080',661311267210542080,153550413,2015.5,129.946556,0.204686,19.769932,0.162611,5.425975,...,NaN,NaN,NaN,NaN,18.200,<NA>,b'N/A',b'N/A',b'N/A',0.191592

df_k2.columns.tolist()

In [80]:
df_k2.loc[idx,['phot_g_mean_mag','k2_teff','k2c_disp','k2c_note']]

        phot_g_mean_mag  k2_teff k2c_disp k2c_note
69            10.131588      NaN   b'N/A'   b'N/A'
546           15.023606      NaN   b'N/A'   b'N/A'
555           14.835970      NaN   b'N/A'   b'N/A'
33358         14.489039      NaN   b'N/A'   b'N/A'
33359         14.991423      NaN   b'N/A'   b'N/A'
...                 ...      ...      ...      ...
398213        12.919633      NaN   b'N/A'   b'N/A'
398215        15.032795      NaN   b'N/A'   b'N/A'
398268        15.664971      NaN   b'N/A'   b'N/A'
420725        17.681662      NaN   b'N/A'   b'N/A'
420726        18.412598      NaN   b'N/A'   b'N/A'

[8823 rows x 4 columns]

In [60]:
idx3=df_nexsci.source_id.isin(df.Source)
idx3.sum()

33

In [56]:
df_nexsci.columns.tolist()

['solution_id',
 'designation',
 'source_id',
 'random_index',
 'gaia_ref_epoch',
 'ra',
 'ra_error',
 'dec',
 'dec_error',
 'parallax',
 'parallax_error',
 'parallax_over_error',
 'pmra',
 'pmra_error',
 'pmdec',
 'pmdec_error',
 'ra_dec_corr',
 'ra_parallax_corr',
 'ra_pmra_corr',
 'ra_pmdec_corr',
 'dec_parallax_corr',
 'dec_pmra_corr',
 'dec_pmdec_corr',
 'parallax_pmra_corr',
 'parallax_pmdec_corr',
 'pmra_pmdec_corr',
 'astrometric_n_obs_al',
 'astrometric_n_obs_ac',
 'astrometric_n_good_obs_al',
 'astrometric_n_bad_obs_al',
 'astrometric_gof_al',
 'astrometric_chi2_al',
 'astrometric_excess_noise',
 'astrometric_excess_noise_sig',
 'astrometric_params_solved',
 'astrometric_primary_flag',
 'astrometric_weight_al',
 'astrometric_pseudo_colour',
 'astrometric_pseudo_colour_error',
 'mean_varpi_factor_al',
 'astrometric_matched_observations',
 'visibility_periods_used',
 'astrometric_sigma5d_max',
 'frame_rotator_object_type',
 'matched_observations',
 'duplicated_source',
 'phot_g_n_obs',
 'phot_g_mean_flux',
 'phot_g_mean_flux_error',
 'phot_g_mean_flux_over_error',
 'phot_g_mean_mag',
 'phot_bp_n_obs',
 'phot_bp_mean_flux',
 'phot_bp_mean_flux_error',
 'phot_bp_mean_flux_over_error',
 'phot_bp_mean_mag',
 'phot_rp_n_obs',
 'phot_rp_mean_flux',
 'phot_rp_mean_flux_error',
 'phot_rp_mean_flux_over_error',
 'phot_rp_mean_mag',
 'phot_bp_rp_excess_factor',
 'phot_proc_mode',
 'bp_rp',
 'bp_g',
 'g_rp',
 'radial_velocity',
 'radial_velocity_error',
 'rv_nb_transits',
 'rv_template_teff',
 'rv_template_logg',
 'rv_template_fe_h',
 'phot_variable_flag',
 'l',
 'b',
 'ecl_lon',
 'ecl_lat',
 'priam_flags',
 'teff_val',
 'teff_percentile_lower',
 'teff_percentile_upper',
 'a_g_val',
 'a_g_percentile_lower',
 'a_g_percentile_upper',
 'e_bp_min_rp_val',
 'e_bp_min_rp_percentile_lower',
 'e_bp_min_rp_percentile_upper',
 'flame_flags',
 'radius_val',
 'radius_percentile_lower',
 'radius_percentile_upper',
 'lum_val',
 'lum_percentile_lower',
 'lum_percentile_upper',
 'datalink_url',
 'epoch_photometry_url',
 'ra_nasa',
 'dec_nasa',
 'pl_name',
 'r_est',
 'r_lo',
 'r_hi',
 'r_length_prior',
 'r_result_flag',
 'r_modality_flag',
 'pl_hostname',
 'pl_letter',
 'pl_discmethod',
 'pl_controvflag',
 'pl_pnum',
 'pl_orbper',
 'pl_orbpererr1',
 'pl_orbpererr2',
 'pl_orbperlim',
 'pl_orbpern',
 'pl_orbsmax',
 'pl_orbsmaxerr1',
 'pl_orbsmaxerr2',
 'pl_orbsmaxlim',
 'pl_orbsmaxn',
 'pl_orbeccen',
 'pl_orbeccenerr1',
 'pl_orbeccenerr2',
 'pl_orbeccenlim',
 'pl_orbeccenn',
 'pl_orbincl',
 'pl_orbinclerr1',
 'pl_orbinclerr2',
 'pl_orbincllim',
 'pl_orbincln',
 'pl_bmassj',
 'pl_bmassjerr1',
 'pl_bmassjerr2',
 'pl_bmassjlim',
 'pl_bmassn',
 'pl_bmassprov',
 'pl_radj',
 'pl_radjerr1',
 'pl_radjerr2',
 'pl_radjlim',
 'pl_radn',
 'pl_dens',
 'pl_denserr1',
 'pl_denserr2',
 'pl_denslim',
 'pl_densn',
 'pl_ttvflag',
 'pl_kepflag',
 'pl_k2flag',
 'st_posn',
 'st_dist',
 'st_disterr1',
 'st_disterr2',
 'st_distlim',
 'st_distn',
 'st_optmag',
 'st_optmagerr',
 'st_optmaglim',
 'st_optband',
 'gaia_gmag',
 'gaia_gmagerr',
 'gaia_gmaglim',
 'st_teff',
 'st_tefferr1',
 'st_tefferr2',
 'st_tefflim',
 'st_teffn',
 'st_mass',
 'st_masserr1',
 'st_masserr2',
 'st_masslim',
 'st_massn',
 'st_rad',
 'st_raderr1',
 'st_raderr2',
 'st_radlim',
 'st_radn',
 'pl_nnotes',
 'rowupdate',
 'pl_facility',
 'pl_tranflag',
 'pl_rvflag',
 'pl_imgflag',
 'pl_astflag',
 'pl_omflag',
 'pl_cbflag',
 'pl_disc',
 'hd_name',
 'hip_name',
 'st_radv',
 'st_radverr1',
 'st_radverr2',
 'st_radvlim',
 'st_radvn',
 'nasa_gaia_ang_dist']

In [63]:
cols=['pl_hostname','pl_discmethod','st_teff','pl_radj','pl_bmassj']
df_nexsci.loc[df_nexsci.source_id.isin(df.Source),cols]

,pl_hostname,pl_discmethod,st_teff,pl_radj,pl_bmassj
12,b'2MASS J04414489+2301513',b'Imaging',NaN,NaN,7.500
23,b'51 Eri',b'Imaging',NaN,NaN,NaN
55,b'BD-13 2130',b'Radial Velocity',4545.00,NaN,9.780
59,b'CHXR 73',b'Imaging',NaN,NaN,12.569
91,b'CT Cha',b'Imaging',NaN,2.200,17.000
93,b'DH Tau',b'Imaging',NaN,NaN,11.000
94,b'EPIC 211822797',b'Transit',4148.21,0.177,NaN
708,b'HIP 78530',b'Imaging',10500.00,NaN,23.000
720,b'IC 4651 9122',b'Radial Velocity',NaN,NaN,6.300
721,b'K2-100',b'Transit',6168.00,0.320,NaN
722,b'K2-101',b'Transit',4819.00,0.178,NaN
723,b'K2-102',b'Transit',4695.00,0.116,NaN
724,b'K2-104',b'Transit',3546.46,0.175,NaN
895,b'K2-231',b'Transit',5695.00,0.223,NaN
931,b'K2-25',b'Transit',3180.00,0.306,NaN
942,b'K2-33',b'Transit',3540.00,0.450,3.700
1020,b'K2-95',b'Transit',3548.00,0.346,NaN
1881,b'Kepler-1627',b'Transit',5445.00,0.329,NaN
2954,b'Kepler-66',b'Transit',5962.00,0.250,NaN
2965,b'Kepler-67',b'Transit',5331.00,0.262,NaN
3335,b'Kepler-970',b'Transit',4511.00,0.247,NaN
3409,b'LkCa 15',b'Imaging',NaN,NaN,NaN
3410,b'LkCa 15',b'Imaging',NaN,NaN,NaN
3431,b'NGC 2682 Sand 978',b'Radial Velocity',4200.00,NaN,2.180
3432,b'NGC 2682 YBP 1194',b'Radial Velocity',5780.00,NaN,0.320
3433,b'NGC 2682 YBP 1514',b'Radial Velocity',5725.00,NaN,0.400
3434,b'NGC 2682 YBP 401',b'Radial Velocity',6165.00,NaN,0.460
3486,b'Pr0211',b'Radial Velocity',5300.00,NaN,1.880
3487,b'Pr0211',b'Radial Velocity',5300.00,NaN,7.790
3494,b'ROXs 12',b'Imaging',3850.00,NaN,16.000
3499,b'TAP 26',b'Radial Velocity',4620.00,NaN,1.660
3515,b'USco CTIO 108',b'Imaging',2700.00,NaN,14.000
3519,b'V830 Tau',b'Radial Velocity',4250.00,NaN,0.700