In [ ]:
from astroquery.ipac.nexsci.nasa_exoplanet_archive import NasaExoplanetArchive
import pandas as pd

redownload = True

fp = '../data/nexsci_data.csv'
if redownload:
    #pstable combines data from the Confirmed Planets and Extended Planet Parameters tables
    tab = NasaExoplanetArchive.query_criteria(table="pscomppars", 
                                             where="discoverymethod like 'Transit'"

                                            ) 
    df.to_csv(fp, index=True)
    df = tab.to_pandas()
else:
    df = pd.read_csv(fp, index_col=0)
    df.index.name = 'index'
df.head()

In [5]:
df.head()

,pl_name,pl_letter,hostname,hd_name,hip_name,tic_id,disc_pubdate,disc_year,discoverymethod,disc_locale,...,sy_pmra,sy_pmraerr1,sy_pmraerr2,sy_pmrastr,x,y,z,htm20,sky_coord.ra,sky_coord.dec
0,Kepler-276 c,c,Kepler-276,,,TIC 138213510,2014-02,2013,Transit,Space,...,7.99553,0.051581,-0.051581,7.9955300&plusmn;0.0515805,0.310575,-0.711954,0.629813,1302657699,293.568197,39.036312
1,Kepler-829 b,b,Kepler-829,,,TIC 123451768,2016-05,2016,Transit,Space,...,7.93777,0.040833,-0.040833,7.9377700&plusmn;0.0408326,0.157566,-0.720680,0.675124,-792260935,282.332831,42.463813
2,K2-283 b,b,K2-283,,,TIC 266017624,2018-12,2018,Transit,Space,...,-10.97340,0.053624,-0.053624,-10.9734000&plusmn;0.0536244,0.959702,0.224997,0.168368,609813555,13.194368,9.692918
3,Kepler-477 b,b,Kepler-477,,,TIC 158633329,2016-05,2016,Transit,Space,...,-26.00000,NaN,NaN,-26.0,0.229185,-0.702544,0.673726,-1968935374,288.067445,42.355305
4,TOI-1260 c,c,TOI-1260,,,TIC 355867695,2021-08,2021,Transit,Space,...,-177.23600,0.036921,-0.036921,-177.2360000&plusmn;0.0369214,-0.376942,0.158885,0.912507,-454174731,157.144071,65.854199
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3936,Kepler-324 c,c,Kepler-324,,,TIC 243271716,2014-03,2014,Transit,Space,...,-2.19729,0.027291,-0.027291,-2.1972900&plusmn;0.0272907,0.183581,-0.620896,0.762093,349022935,286.471447,49.649093
3937,TOI-5174 b,b,TOI-5174,,,TIC 49428710,2022-11,2022,Transit,Space,...,6.78830,0.084873,-0.084873,6.7883000&plusmn;0.0848728,-0.994100,0.102564,-0.035307,-1359233275,174.109497,-2.023351
3938,TOI-5542 b,b,TOI-5542,,,TIC 466206508,2022-09,2022,Transit,Space,...,-6.14486,0.051566,-0.051566,-6.1448600&plusmn;0.0515661,0.261493,-0.405783,-0.875764,-801896825,302.798423,-61.135466
3939,TOI-411 b,b,TOI-411,,,TIC 100990000,2022-09,2022,Transit,Space,...,-51.66370,0.044345,-0.044345,-51.6637000&plusmn;0.0443452,0.422994,0.600066,-0.678968,488407113,54.819538,-42.763028
3940,NGTS-25 b,b,NGTS-25,,,TIC 290742484,2022-11,2022,Transit,Ground,...,5.17449,0.043408,-0.043408,5.1744900&plusmn;0.0434075,0.472001,-0.616943,-0.629759,355831039,307.418298,-39.032357

In [24]:
idx = (df['st_age']<1) & (df['st_ageerr1']/df['st_age']<0.1) & (df['st_ageerr2']/df['st_age']<0.1)
df[idx].hostname.unique()

array(['HD 63433', 'K2-25', 'K2-100', 'Qatar-5', 'Qatar-3', 'DS Tuc A',
       'K2-101', 'K2-104', 'Qatar-4', 'Kepler-970', 'CoRoT-18', 'K2-136',
       'K2-102', 'K2-95', 'EPIC 211822797', 'Kepler-1928'], dtype=object)

In [6]:
age = pd.Series({'K2-33': 0.010, #in U.Sco.
                 'TOI-1227': 0.011, #in LCC
                 'HIP 67522': 0.017, #Rizzuto+20
                 'Au Mic': 0.022, #Plavchan+19,Klein+20
                 'HD 109833': 0.027, #TOI 1097
                 'V1298 Tau': 0.028, #'K2-309'
                 'KOI-7368': 0.036,
                 'TOI-837': 0.035, #in IC 2602
                 'KOI-7913': 0.036, #Bouma
                 'Kepler-1627A': 0.038, #Bouma+2022
                 'DS Tuc A': 0.045, #'TOI-200' in Tuc
                 'Kepler-1643': 0.048, #Bouma
                 'TOI-942': 0.090, #20-160, Zhou+2020, Carleo+2020b
                 'TOI-251': 0.180, #field, Zhou+2020
                 'Kepler-970 ': 0.1, #Barber
                 'Kepler-1928': 0.1, #Barber
                 'TOI-451': 0.120, #in Psc-Eri, Newton+2021     
                 'HIP 94235': 0.1, #'TOI-4399': 0.1, #
                 'HD 73583': 0.48, #TOI-560
                 'K2-233': 0.5,
                 'K2-25': 0.700, #Mann+2016a, David+2016 in Hyades
                 'K2-95': 0.790, #in Praesepe
                 'K2-100': 0.790, 'K2-101': 0.790, 'K2-102': 0.790, 'K2-103': 0.790, 'K2-104': 0.790, #in Praesepe
                 'K2-136': 0.700, #in Hyades
                 'K2-264': 0.790, #in Praesepe
                 'K2-284': 0.120, #field, may be Cas-Tau
                 'HD 110082': 0.250, #TOI-1098, Tofflemier+2021
                 'HD 63433': 0.400, #TOI-1726, Mann+2020
                }, name='st_age')
age

K2-33           0.010
TOI-1227        0.011
HIP 67522       0.017
Au Mic          0.022
HD 109833       0.027
V1298 Tau       0.028
KOI-7368        0.036
TOI-837         0.035
KOI-7913        0.036
Kepler-1627A    0.038
DS Tuc A        0.045
Kepler-1643     0.048
TOI-942         0.090
TOI-251         0.180
Kepler-970      0.100
Kepler-1928     0.100
TOI-451         0.120
TOI-4399        0.100
K2-25           0.700
K2-95           0.790
K2-100          0.790
K2-101          0.790
K2-102          0.790
K2-103          0.790
K2-104          0.790
K2-136          0.700
K2-264          0.790
K2-284          0.120
HD 110082       0.250
HD 63433        0.400
Name: st_age, dtype: float64

In [9]:
names = age.index.tolist()
df2 = pd.merge(df, age, left_on='hostname', left_index=False, right_index=True)
idx = df2['hostname'].isin(names)
df2[idx].hostname.unique()

array(['HD 109833', 'TOI-942', 'HD 63433', 'HIP 67522', 'K2-25', 'K2-100',
       'V1298 Tau', 'DS Tuc A', 'K2-264', 'K2-101', 'K2-104', 'TOI-251',
       'Kepler-1643', 'KOI-7368', 'HD 110082', 'TOI-451', 'K2-136',
       'TOI-837', 'K2-102', 'TOI-1227', 'K2-95', 'K2-284', 'K2-33',
       'Kepler-1928'], dtype=object)